# Generated by Django 2.2.4 on 2019-08-18 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='mon',
        ),
    ]
